version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: nest-graphql-postgres
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs-graphql
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: